Repository usadellab/GeneExpressionPlots, pull requests merged in 2021-06, with the labels that each got.

#66 chore: vite migration
  .env-cmdrc.js
  .env.development
  .env.production
  .eslintrc
  README.md
  babel.config.json
  index.html
  package.json
  public/hero-icons.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  public/svg4everybody.js
  src/App.jsx
  src/components/AppIcon.jsx
  src/layout/Navigation.jsx
  src/main.jsx
  src/modules/data/pages/DataView.jsx
  src/modules/plotly/components/PlotlyPlot.jsx
  src/modules/plotly/layout/PlotsLayout.jsx
  src/modules/plotly/pages/PlotsView.jsx
  src/store/settings.js
  static/.gitkeep
  vite.config.js
  webpack.config.js
  yarn.lock
Labels: chore

#69 feat: manual count unit
  src/modules/data/components/GroupForm.jsx
  src/modules/data/components/TableForm.jsx
Labels: feature

#70 fix: restore preload functionality
  .env.development
  .env.production
  .gitignore
  examples/GXP_settings.json
  examples/gxp_settings.json
  index.html
  src/modules/data/components/TableForm.jsx
  src/modules/plotly/components/PlotsForm.jsx
  src/store/settings.js
  src/utils/plotsHelper.js
Labels: feature

#73 feat: Cypress testing
  .eslintignore
  .gitignore
  README.md
  cypress.json
  cypress/babel.config.js
  cypress/fixtures/table_no_header.tsv
  cypress/fixtures/table_with_header.tsv
  cypress/plugins/index.d.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/support/index.ts
  cypress/tests/components/AppAnchor.test.tsx
  cypress/tests/integration/enrichment.test.ts
  cypress/tests/integration/heatmap.test.ts
  cypress/tsconfig.json
  jest.setup.js
  package.json
  tests/enrichment_analyses.test.js
  tests/heatmap.test.js
  yarn.lock
Labels: chore, dependencies

#74 tests: support path aliases in cypress tests
  cypress/plugins/index.ts
  cypress/tests/components/AppAnchor.test.tsx
  cypress/tests/integration/enrichment.test.ts
  cypress/tests/integration/heatmap.test.ts
  cypress/tsconfig.json
  cypress/webpack.config.ts
  package.json
  yarn.lock
Labels: chore, tests

#75 chore: use plotly from npm
  .eslintignore
  index.html
  package.json
  postcss.config.js
  src/modules/plotly/components/PlotlyPlot.jsx
  src/store/plot-store.js
  src/utils/plotsHelper.js
  vite.config.js
  yarn.lock
Labels: chore

#79 refactor: plot store
  package.json
  src/pages/plots/components/PlotlyPlot.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.js
  src/store/plot-store.ts
  src/store/settings.ts
  yarn.lock
Labels: refactor

#80 refactor: Plot components
  src/components/cards/GeneCard.jsx
  src/components/cards/GeneCard.tsx
  src/pages/plots/components/PlotCaption.jsx
  src/pages/plots/components/PlotCaption.tsx
  src/pages/plots/components/PlotlyPlot.tsx
  src/pages/plots/components/individual-lines-form.tsx
  src/pages/plots/components/stacked-lines-form.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/store/settings.ts
  src/types/plots.ts
  src/utils/plots/bars-and-individual-lines.ts
  src/utils/plots/multi-gene-bar.ts
  src/utils/plots/multi-gene-individual-lines.ts
  src/utils/plots/single-gene-bar.ts
  src/utils/plots/single-gene-individual-lines.ts
  src/utils/plots/stacked-lines.ts
Labels: refactor

#81 feat: heatmap plot
  package.json
  src/components/nav-sidebar/sidebar-nav.tsx
  src/ml-distance.d.ts
  src/pages/data/data-files.tsx
  src/pages/plots/components/PlotlyPlot.tsx
  src/pages/plots/components/heatmap-form.tsx
  src/pages/plots/components/heatmap-plot.tsx
  src/pages/plots/components/plot-container.tsx
  src/pages/plots/plots-home.tsx
  src/store/dataframe.js
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/heatmap.js
  src/utils/plots/heatmap.ts
  src/utils/plotsHelper.js
  yarn.lock
Labels: chore, dependencies, feature

#82 refactor: use plot-container for plotly plots
  src/css/plotly.css
  src/pages/plots/components/PlotlyPlot.tsx
  src/pages/plots/components/heatmap-plot.tsx
  src/pages/plots/components/plot-container.tsx
  src/pages/plots/plots-home.tsx
Labels: bug, refactor

#83 refactor: port dataframe and remaining utilities to typescript
  src/layout/Navigation.jsx
  src/pages/data/data-files.tsx
  src/store/data-store.ts
  src/store/dataframe.js
  src/store/dataframe.ts
  src/utils/collection.js
  src/utils/collection.ts
  src/utils/color.ts
  src/utils/plots/heatmap.ts
  src/utils/plotsHelper.js
  src/utils/reducers.ts
  src/utils/validation.js
  src/utils/validation.ts
Labels: refactor

#84 Readd pca
  src/pages/plots/components/PlotlyPlot.tsx
  src/pages/plots/components/pca-form.tsx
  src/pages/plots/components/pca-plot.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/color.ts
  src/utils/plots/pca.ts
Labels: bug, feature, refactor

#85 Gene browser tool
  src/app-routes.tsx
  src/components/formik-number/formik-number.tsx
  src/components/formik-number/index.tsx
  src/components/gene-card/gene-card.tsx
  src/components/gene-card/index.ts
  src/modules/plotly/components/PlotCaption.jsx
  src/modules/tools/ToolsModule.jsx
  src/modules/tools/ToolsRoutes.jsx
  src/modules/tools/components/GeneDetails.jsx
  src/modules/tools/pages/GeneBrowser.jsx
  src/modules/tools/pages/ToolsHome.jsx
  src/pages/plots/components/PlotCaption.tsx
  src/pages/tools/components/gene-browser-card.tsx
  src/pages/tools/components/gene-browser-form.tsx
  src/pages/tools/components/gene-browser.tsx
  src/pages/tools/components/gene-details.tsx
  src/pages/tools/tools-home.tsx
  src/pages/tools/tools-routes.tsx
Labels: feature, refactor

#86 Heatmap title tooltip
  package.json
  src/pages/plots/components/heatmap-plot.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  yarn.lock
Labels: feature

#87 heatmap-left-axis
  src/pages/plots/components/heatmap-plot.tsx
Labels: feature

#89 feat: heatmap dendro
  package.json
  src/pages/plots/components/heatmap-plot.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/plots/heatmap.ts
  yarn.lock
Labels: feature

#90 feat: plots sidebar layout, icons, and delete functionality
  src/pages/plots/plots-home.tsx
Labels: feature
