Repository usadellab/GeneExpressionPlots, pull requests merged in 2021-11, with the labels that each got.

#129 feat: parse mercator
  cypress/tests/integration/mercator.test.ts
  src/pages/tools/components/mapman-tool.tsx
  src/pages/tools/components/mercator-form.tsx
  src/pages/tools/tools-home.tsx
  src/pages/tools/tools-routes.tsx
  src/store/dataframe.ts
  src/utils/parser.ts
Labels: feature

#130 Mapman
  björns-code.html
  package.json
  public/mapman-templates/X4.3_Amino_acid_metabolism_R3.0.svg
  public/mapman-templates/X4.3_Amino_acid_metabolism_R3.0.xml
  public/mapman-templates/X4.3_Carbohydrate_metabolism_R3.0.svg
  public/mapman-templates/X4.3_Carbohydrate_metabolism_R3.0.xml
  public/mapman-templates/X4.3_Cellular_respiration_R3.0.svg
  public/mapman-templates/X4.3_Cellular_respiration_R3.0.xml
  public/mapman-templates/X4.3_Coenzyme_metabolism_R3.0.svg
  public/mapman-templates/X4.3_Coenzyme_metabolism_R3.0.xml
  public/mapman-templates/X4.3_GA_synthesis_R3.0.svg
  public/mapman-templates/X4.3_GA_synthesis_R3.0.xml
  public/mapman-templates/X4.3_JA_synthesis_R3.0.svg
  public/mapman-templates/X4.3_JA_synthesis_R3.0.xml
  public/mapman-templates/X4.3_Lignin_R3.0.svg
  public/mapman-templates/X4.3_Lignin_R3.0.xml
  public/mapman-templates/X4.3_Lipid_metabolism_R3.0.svg
  public/mapman-templates/X4.3_Lipid_metabolism_R3.0.xml
  public/mapman-templates/X4.3_Metabolism_overview_R3.0.svg
  public/mapman-templates/X4.3_Metabolism_overview_R3.0.xml
  public/mapman-templates/X4.3_Nucleotide_metabolism_R3.0.svg
  public/mapman-templates/X4.3_Nucleotide_metabolism_R3.0.xml
  public/mapman-templates/X4.3_Photosynthesis_R3.0.svg
  public/mapman-templates/X4.3_Photosynthesis_R3.0.xml
  public/mapman-templates/X4.3_Polyamine_metabolism_R3.0.svg
  public/mapman-templates/X4.3_Polyamine_metabolism_R3.0.xml
  public/mapman-templates/X4.3_Secondary_metabolism_R3.0.svg
  public/mapman-templates/X4.3_Secondary_metabolism_R3.0.xml
  public/mapman-templates/X4.3_Tetrapyrrole_biosynthesis_R3.0.svg
  public/mapman-templates/X4.3_Tetrapyrrole_biosynthesis_R3.0.xml
  public/mapman-templates/X4.3_Tocopherol_biosynthesis_R3.0.svg
  public/mapman-templates/X4.3_Tocopherol_biosynthesis_R3.0.xml
  public/mapman-templates/X4.3_Vesicle_trafficking_R3.0.svg
  public/mapman-templates/X4.3_Vesicle_trafficking_R3.0.xml
  public/upload_info_table.tsv
  src/pages/plots/components/mapman-form.tsx
  src/pages/plots/components/mapman-plot.tsx
  src/pages/plots/components/plot-container.tsx
  src/pages/plots/plots-home.tsx
  src/store/dataframe.ts
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/plots/mapman-xml-domparser.ts
  yarn.lock
Labels: feature

#132 fix: typos, labels
  src/pages/plots/components/bars-form.tsx
  src/pages/plots/components/heatmap-form.tsx
  src/pages/plots/components/individual-lines-form.tsx
  src/pages/plots/components/pca-form.tsx
  src/pages/plots/components/stacked-lines-form.tsx
  src/pages/plots/plots-home.tsx
  src/pages/tools/tools-home.tsx
Labels: refactor

#133 feat: Mapman todos
  björns-code.html
  public/mapman-templates/X4.3_Metabolism_overview_R3.0.xml
  src/components/formik-field/formik-field.tsx
  src/pages/plots/components/mapman-form.tsx
  src/pages/plots/components/mapman-plot.tsx
  src/pages/plots/plots-home.tsx
  src/pages/tools/components/gene-browser-card.tsx
  src/pages/tools/components/mapman-tool.tsx
  src/pages/tools/tools-home.tsx
  src/store/dataframe.ts
  src/store/plot-store.ts
  src/types/plots.ts
Labels: feature, refactor

#134 Mapman plot refactor
  src/pages/plots/components/mapman-plot.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/plots/mapman.ts
Labels: feature, refactor

#135 Chore: update packages
  package.json
  src/app-home.tsx
  src/app-routes.tsx
  src/pages/data/data-routes.tsx
  src/pages/info/info-routes.tsx
  src/pages/plots/plots-routes.tsx
  src/pages/tools/tools-routes.tsx
  src/store/enrichment-store.ts
  src/store/plot-store.ts
  yarn.lock
Labels: bug, chore

#138 refactor: Add validation for Numeric column, Add numeric validation function to dataframe, Update Mapman form pass numeric column validation
  src/pages/plots/components/mapman-form.tsx
  src/pages/tools/components/mapman-tool.tsx
  src/store/dataframe.ts
  src/utils/validation.ts
Labels: bug, feature

#139 feat: Todos 18 nov
  src/components/gene-card/gene-card.tsx
  src/pages/data/data-files.tsx
  src/pages/plots/components/color-legend.tsx
  src/pages/plots/components/heatmap-plot.tsx
  src/pages/plots/components/mapman-form.tsx
  src/pages/plots/components/mapman-plot.tsx
  src/pages/plots/plots-home.tsx
  src/pages/tools/components/gene-browser-card.tsx
  src/pages/tools/components/mapman-tool.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/mercator.ts
  src/utils/plots/mapman.ts
Labels: bug, feature, refactor

#141 merge: latest development
  src/pages/plots/components/color-legend.tsx
  src/pages/plots/components/heatmap-plot.tsx
  src/pages/plots/plots-home.tsx
Labels: bug, feature
