Repository usadellab/GeneExpressionPlots, pull requests merged in 2021-07, with the labels that each got.

#92 feat: Info routes
  src/app-routes.tsx
  src/components/link-card/index.ts
  src/components/link-card/link-card.tsx
  src/pages/info/info-home.tsx
  src/pages/info/info-routes.tsx
Labels: feature

#91 feat: app layout and flow tweaks
  src/app-home.tsx
  src/app-routes.tsx
  src/components/nav-sidebar/sidebar-button.tsx
  src/components/nav-sidebar/sidebar-nav.tsx
  src/components/nav-topbar/topbar-link.tsx
  src/layouts/app-layout/app-layout.tsx
  src/pages/data/data-files.tsx
  src/pages/data/data-routes.tsx
  src/pages/plots/plots-home.tsx
  src/pages/tools/components/gene-browser.tsx
Labels: bug, feature

#93 feat: plot actions
  src/pages/plots/components/PlotlyPlot.tsx
  src/pages/plots/components/heatmap-plot.tsx
  src/pages/plots/components/pca-plot.tsx
  src/pages/plots/components/plot-container.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/svg.ts
Labels: feature

#94 feat: accession validation
  src/pages/plots/components/bars-form.tsx
  src/pages/plots/components/individual-lines-form.tsx
  src/pages/plots/components/stacked-lines-form.tsx
Labels: feature

#95 chore: Pre deploy cleanup
  src/components/AppAnchor.tsx
  src/components/AppButton.tsx
  src/components/AppCheckbox.tsx
  src/components/AppDatalist.jsx
  src/components/AppFile.jsx
  src/components/AppIcon.jsx
  src/components/AppLink.jsx
  src/components/AppModal.jsx
  src/components/AppNumber.jsx
  src/components/AppOverlay.jsx
  src/components/AppRipple.jsx
  src/components/AppSelect.jsx
  src/components/AppSpinner.jsx
  src/components/AppSwitch.jsx
  src/components/AppText.jsx
  src/components/AppTextArea.jsx
  src/components/BaseInput.jsx
  src/layout/AppLayout.jsx
  src/layout/Navigation.jsx
  src/layout/NavigationItem.jsx
  src/layout/TopBar.jsx
  src/modules/data/components/GroupForm.jsx
  src/modules/plotly/PlotsHome.jsx
  src/modules/plotly/PlotsRoutes.jsx
  src/modules/plotly/components/PlotCaption.jsx
  src/modules/plotly/components/PlotlyPlot.jsx
  src/modules/plotly/components/PlotsForm.jsx
  src/modules/plotly/layout/PlotsLayout.jsx
  src/modules/plotly/pages/PlotsView.jsx
  src/pages/plots/components/PlotsForm.jsx
  src/pages/plots/components/plot-caption.tsx
  src/pages/plots/components/plotly-plot.tsx
  src/pages/plots/plots-home.tsx
  src/utils/plots/multi-gene-individual-lines.ts
  src/utils/plots/stacked-lines.ts
  src/utils/plotsHelper.js
Labels: chore

#98 fix: missing validateOnBlur for data forms
  src/pages/data/components/export-form.tsx
  src/pages/data/components/import-form.tsx
  src/pages/data/components/info-form.tsx
  src/pages/data/components/xtable-form.tsx
Labels: bug

#99 feat: color by for stacked lines form
  src/components/formik-radio/formik-radio.tsx
  src/components/formik-radio/index.ts
  src/pages/plots/components/stacked-lines-form.tsx
  src/pages/plots/plots-home.tsx
Labels: feature

#101 feat: Remove modebar buttons
  src/pages/plots/components/pca-plot.tsx
  src/pages/plots/components/plotly-plot.tsx
Labels: feature

#100 feat: preload tweaks
  .env.development
  .env.production
  src/app.tsx
  src/pages/data/components/repl-card.tsx
  src/pages/data/data-files.tsx
  src/pages/plots/components/image-form.tsx
  src/pages/plots/components/image-plot.tsx
  src/pages/plots/components/plot-container.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
Labels: feature

#102 fix: tests failing
  cypress/tests/components/AppAnchor.test.tsx
  cypress/tests/integration/enrichment.test.ts
  cypress/tests/integration/heatmap.test.ts
  cypress/tsconfig.json
  package.json
  src/store/dataframe.ts
  src/utils/enrichment_analyses.js
  src/utils/plots/heatmap.ts
  tests/heatmap.test.js
  yarn.lock
Labels: bug, chore

#103 feat: app state
  src/app.tsx
  src/layouts/app-layout/app-layout.tsx
  src/utils/fetch.ts
Labels: feature, refactor

#104 feat: update main to latest version
  .env.development
  .env.production
  cypress/tests/components/AppAnchor.test.tsx
  cypress/tests/integration/enrichment.test.ts
  cypress/tests/integration/heatmap.test.ts
  cypress/tsconfig.json
  package.json
  src/app.tsx
  src/components/formik-radio/formik-radio.tsx
  src/components/formik-radio/index.ts
  src/layouts/app-layout/app-layout.tsx
  src/pages/data/components/export-form.tsx
  src/pages/data/components/import-form.tsx
  src/pages/data/components/info-form.tsx
  src/pages/data/components/repl-card.tsx
  src/pages/data/components/xtable-form.tsx
  src/pages/data/data-files.tsx
  src/pages/plots/components/image-form.tsx
  src/pages/plots/components/image-plot.tsx
  src/pages/plots/components/pca-plot.tsx
  src/pages/plots/components/plot-container.tsx
  src/pages/plots/components/plotly-plot.tsx
  src/pages/plots/components/stacked-lines-form.tsx
  src/pages/plots/plots-home.tsx
  src/store/dataframe.ts
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/enrichment_analyses.js
  src/utils/fetch.ts
  src/utils/plots/heatmap.ts
  tests/heatmap.test.js
  yarn.lock
Labels: bug, dependencies, feature, refactor, tests

#105 hotfix: optimize accession matching
  src/hooks/match-accesion.ts
Labels: bug

#106 feat: webworkers for heatmap and pca
  src/store/dataframe.ts
  src/store/plot-store.ts
  src/utils/color.ts
  src/utils/plots/heatmap.ts
  src/utils/plots/pca.ts
  src/utils/store.ts
  src/workers/heatmap.ts
  src/workers/pca.ts
Labels: feature, refactor

#107 merge: latest develop
  src/pages/plots/components/heatmap-plot.tsx
  src/store/dataframe.ts
  src/store/plot-store.ts
  src/utils/color.ts
  src/utils/plots/heatmap.ts
  src/utils/plots/pca.ts
  src/utils/store.ts
  src/workers/heatmap.ts
  src/workers/pca.ts
Labels: bug, feature

#108 feat: load static example data
  public/upload_expression_table.tsv
  public/upload_info_table.tsv
  src/pages/data/data-files.tsx
Labels: feature

#109 feat: Enrichment analyses
  .eslintignore
  cypress/tests/integration/enrichment.test.ts
  examples/GXP_data.zip
  examples/upload_info_table.tsv
  package.json
  public/gsl.wasm
  public/upload_info_table.tsv
  src/components/formik-select/formik-select.tsx
  src/components/formik-select/index.ts
  src/pages/data/data-files.tsx
  src/pages/tools/components/enrichment-details.tsx
  src/pages/tools/components/enrichment-form.tsx
  src/pages/tools/components/enrichment-tool.tsx
  src/pages/tools/tools-home.tsx
  src/pages/tools/tools-routes.tsx
  src/store/enrichment-store.ts
  src/types/enrichment.ts
  src/utils/enrichment_analysis.ts
  src/utils/fishers-exact-test.ts
  src/utils/gsl/gsl.js
  src/utils/parser.ts
  src/workers/enrichment.ts
  yarn.lock
Labels: feature

#110 feat: Heatmap transpose matrix + filter for genes
  src/components/formik-radio/formik-radio.tsx
  src/components/formik-replicate/formik-replicate.tsx
  src/components/formik-replicate/index.tsx
  src/hooks/index.ts
  src/hooks/match-replicate.ts
  src/pages/plots/components/heatmap-form.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/plots/heatmap.ts
  src/utils/store.ts
  src/workers/heatmap.ts
Labels: feature

#111 feat: pca transpose matrix + filter genes/replicates
  src/pages/plots/components/pca-form.tsx
  src/pages/plots/plots-home.tsx
  src/store/plot-store.ts
  src/types/plots.ts
  src/utils/color.ts
  src/utils/plots/pca.ts
  src/workers/pca.ts
Labels: feature
